id: P424BFF45
initial_creation_type: input
source_metadata:
  title: Jetsün Mingyur Paldrön
  language: en
  description: 'Texts by and about Jetsün Mingyur Paldrön (rje btsun mi ''gyur dpal
    sgron, 1699–1769), daughter of Minling Terchen Gyurme Dorje:'
  volume:
    bd7aca623127452d829cd0e0d49de91d:
      title: Mindrolling Lineage Prayer
      parent: Lineage Prayers
created_at: '2022-03-01T00:01:59.903857'
last_modified_at: '2022-03-01T00:01:59.903863'
